server {
  server_tokens off;

  gzip on;
  gzip_types text/plain application/xml;

  server_name _; # Catch-all
  root /usr/share/nginx/html;

  proxy_buffer_size 128k;
  proxy_buffers 8 128k;
  proxy_busy_buffers_size 256k;
  proxy_temp_file_write_size 256k;
  client_header_buffer_size 64k;
  large_client_header_buffers 4 64k;
  client_max_body_size 100M;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
